# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX & Tooling
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# Kotlin & KSP
kotlin.code.style=official
kapt.incremental.apt=false
ksp.incremental=true

